### ISSUE TITLE
1.2.3 Release Checklist

### ISSUE THREAD

**Issue by glennblock** [splunk/splunk-sdk-javascript#27]
# Splunk JavaScript SDK Release Instructions

These are instructions on the various steps necessary to cut out a new
release of the Splunk JavaScript SDK. Even though the instructions are public,
these steps are only meant to be taken by the SDK maintainers.
### Prerequisites
- [ ] Read through all of these release instructions.
  - Update if necessary. (For example, the version numbers will need updating.)
  - For updates that could apply to other SDKs as well, update the release instructions page for every other SDK.
- [x] Update changelog.
- [x] Run test suite on full test matrix.
- [x] Run all examples.
- [x] Run all dev.splunk.com code samples.
- [x] Remove old temporary branches. This includes feature branches, old release branches, and most branches that have been merged to develop.
  - (Exception: The "promises-old" branch in the JavaScript SDK should be retained for the time being.)
### Release Steps
- [x] Create release branch off of develop (`release/1.2.3`).
  - `git checkout develop`
  - `git pull`
  - `git checkout -b release/1.2.3`
- [x] Update the version number:
  - Set `version` key in `package.json` to `1.2.3`.
    (This needs to be a 3-component string.)
- [x] Regenerate compiled files and check into repository.
  - `./sdkdo compile`
  - Commit changes.
- [x] Make sure the version number change didn't break anything:
  - Install the SDK in a clean VM.
  - Run test suite.
  - Run the SDK examples.
- [x] Merge to `master` locally. Ensure the commit message is "Release 1.2.3".
  - `git checkout master`
  - `git merge --no-ff -m "Release 1.2.3" release/1.2.3`
- [x] Tag the above commit as `1.2.3`. (This needs to be a 3-component string.)
  - `git tag 1.2.3`
- [x] Push the `master` and the `1.2.3` tag to GitHub.
  - `git push origin master`
  - `git push --tags`
- [x] Upload the SDK to NPM repository:
  - `npm adduser`
    - Credentials are here: [http://eswiki.splunk.com/JavaScript_SDK_Release](http://eswiki.splunk.com/JavaScript_SDK_Release)
  - `npm publish`
- [x] Delete the release branch:
  - `git push origin :release/1.2.3`
  - `git branch -d release/1.2.3`
- [ ] Sanity check that released version works:
  - _Check with the Product Manager for what should be done here. (And update this bullet with the decision!)_
- [ ] Create a ZIP of the SDK and send it to your Docs team:
  - Make sure the file reflects the current version (for example, splunk-splunk-sdk-javascript-1.2.3.zip).
  - Docs team will get the ZIP file posted to Dev Portal.
- [ ] Work with Docs team to:
  - Post ZIP file.
  - Update Readme. For point releases, the version number needs to be updated at a minimum.
  - Update Changelog, includes a list of changes for the current version.
  - Update Dev Portal and push. For point releases, the "What's new" page and download links need to be updated at the very least.
  - Publish API Reference (docs.splunk.com/Documentation/SDK).
  - Create both MD5 and SHA-512 hashes from _final_ ZIP download. Docs will contact the Web team to upload these files.
- [ ] Hand off to marketing to announce. See next section.
### Announce!

Hurrah, the new release is basically done! You can now announce it on the
following channels:
- Twitter (@splunkdev, maybe @splunk)
- Google Groups (splunkdev)
- Dev Portal (http://dev.splunk.com)
- Dev Blog (http://blogs.splunk.com/dev)
